appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IOvwVY4CWGXvgo7Me8nu55R6EAJkXW8j2OmT3vPhC9/46j8WY60pVbHlO99lIghwGIsKsB88TdHM0NSUZlZYTHGtDAu5SQ72/Occ051fb7vOUliSRoF7m4FMWdHyqqWcK3B/z3JGq/rC/mabGoHAtmdqE9e0BQ0EiG3CyiRaYbNF1U+neGL886plJa++yz/Pwgk0oyQRmW3D1EGS+LAxH9xpuK72JWYrf6u8cPDaTJGx4V8Frz+Othz2ZJObd1eN8NjgssE2enyx4Ym+C9GIbk3+LjbdeCMPMRTyqTL3EDHKVWcazHNkt/iNATNSmqD8gv7n7Xtpd2zn/isyOzKtWXdcoXcEVUOT5KYMQPwECNBBWQSWRWaWiPVpxfB++f2QIacbhwGm3t212rzsyBVXMgqFfB3X3xssX9zsmS1n4M9+B6FJj/Hlp1hcg0j+Yu8OQ1KXlwtyLkvFjsiqRzOUUK/XepGn1iltEGEi4F/rClka+8ilNljcA9JqVGeuhznWstMR+GN9SPqp0GS14VEd1UwFpc2eCgRZfOOzv5MKAfeYb5hOSrXZlDNTZ1cjdLlua8XIICCTM8NbJPeTwWhscJVoBmmGfvGYU57tBXDdHyD6VTlYE0AZx5ThvldE7wT7bZibCSG/PLvrD7p8La6WwaFguD/4g7gpmcL8LebVovY=}
